server:
  port: 8080

spring:
  application:
    name: study-redis-with-jwt

  security:
    enabled: true
    # user 설정 제거 - 데이터베이스 기반 인증 사용

  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: true
  cache:
    type: redis
    redis:
      time-to-live: 60s   #60초후 캐시 자동 만료 설정
  # 세션 설정
  session:
    store-type: redis # (jdbc:db에 저장, redis: redis에 저장, none: 기본 tomcat session 메모리에 저장. )


  # H2 Database 설정
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # H2 Console 설정
  h2:
    console:
      enabled: true
      path: /h2-console


  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # Hibernate가 SQL 초기화를 처리하지 않도록 설정
    defer-datasource-initialization: true


  # SQL 초기화 설정
  sql:
    init:
      mode: always
      platform: h2
      # schema.sql과 data.sql 명시적으로 지정
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      # SQL 실행 시점을 명시적으로 설정
      continue-on-error: false



